// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUE8jASSH1K1qM8Tge1eBnQrQXiyMLYwY',
    appId: '1:6118592177:android:d79f1848eaf07c4ae31c90',
    messagingSenderId: '6118592177',
    projectId: 'sport-up-5f954',
    storageBucket: 'sport-up-5f954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAM-nhbnkQMUtTjRMMZ-oGX1CahC_OFvM',
    appId: '1:6118592177:ios:6d1a33fff32a2be6e31c90',
    messagingSenderId: '6118592177',
    projectId: 'sport-up-5f954',
    storageBucket: 'sport-up-5f954.appspot.com',
    androidClientId: '6118592177-8a14o46bkqvvqquqqu5ffoaatok0cj15.apps.googleusercontent.com',
    iosClientId: '6118592177-3konr098556bvac2uo4mb2e742vpgg9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApplication',
  );
}
